export enum Errors {
  MISSING_BUCKET_NAME = "BUCKET NAME IS REQUIRED",
  MISSING_TABLE_NAME = "TABLE NAME IS REQUIRED",
  MISSING_VALUE_CASE = "INVALID BADGE, NO CORRESPONDING VALUE CASE",
  MISSING_ORGANIZATION = "INVALID BADGE, NO CORRESPONDING ORGANIZATION",
  UNKNOWN_ORGANIZATION = "YOUR ORGANIZATION HAS NOT REGISTERED YET",
  UNAPPROVED_ORGANIZATION = "YOUR ORGANIZATION IS NOT YET APPROVED",
  DUPLICATE_BADGE_APPLICATION = "YOUR ORGANIZATION ALREADY APPLIED FOR THIS BADGE",
  DUPLICATE_ORGANIZATION_REGISTRATION = "YOUR ORGANIZATION ALREADY REGISTERED",
  INVALID_APPROVAL_TOKEN = "INVALID APPROVAL TOKEN FOR THIS ORGANIZATION",
  MISSING_ISSUER = "INVALID BADGE, NO CORRESPONDING ISSUER",
  MISSING_LOCALIZATION = "THIS VALUECASE IS NOT TRANSLATED IN THE LANGUAGE THAT YOU REQUESTED",
  MISSING_PRIVATE_KEY = "NO PRIVATE KEY SET",
}
