export enum Errors {
  MISSING_BUCKET_NAME = "BUCKET NAME IS REQUIRED",
  MISSING_TABLE_NAME = "TABLE NAME IS REQUIRED",
  MISSING_VALUE_CASE = "INVALID BADGE, NO CORRESPONDING VALUE CASE",
  MISSING_ORGANIZATION = "INVALID BADGE, NO CORRESPONDING ORGANIZATION",
  MISSING_ISSUER = "INVALID BADGE, NO CORRESPONDING ISSUER",
  MISSING_LOCALIZATION = "THIS VALUECASE IS NOT TRANSLATED IN THE LANGUAGE THAT YOU REQUESTED",
  MISSING_PRIVATE_KEY = "NO PRIVATE KEY SET",
}
